import Footer from './_components/footer';
import Header from './_components/header';
import './styles/global.css';

export const metadata = {
  title: 'Leonardo Valdetaro - Front-End Developer',
  description: 'Leonardo Valdetaro - Front-End Developer, Designer and Content Creator',
  icons: {
    icon: '/favicon.ico'
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="Generated by create Leonardo Valdetaro" />
        <link rel="icon" href="/favicon.png" type="image/png" />
      </head>

      <body>
        <main className='mainContainer'>
          <Header />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  )
}
